#!/bin/bash
set -e
export ROOTPASSWORD=@MYSQL_ROOT_PASSWORD
mysql -uroot -p @MYSQL_ROOT_PASSWORD <<-EOSQL
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON @MYSQL_DATABASE.* TO '@MYSQL_USER'@'localhost';
EOSQL
